In [3]:
from statsbombpy import sb

competitions = sb.competitions()
competitions.head()

C:\Users\georg\OneDrive\Desktop\Portfolio\womens-football-dashboard\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [2]:
womens = competitions[competitions["competition_gender"] == "female"]
womens[["competition_name", "season_name", "competition_id", "season_id"]]

           competition_name season_name  competition_id  season_id
25  FA Women's Super League   2023/2024              37        281
26  FA Women's Super League   2020/2021              37         90
27  FA Women's Super League   2019/2020              37         42
28  FA Women's Super League   2018/2019              37          4
38        Frauen Bundesliga   2023/2024             135        281
58                   Liga F   2023/2024             182        281
66                     NWSL        2023              49        107
67                     NWSL        2018              49          3
72            Serie A Women   2023/2024             131        281
76        UEFA Women's Euro        2025              53        315
77        UEFA Women's Euro        2022              53        106
78        Women's World Cup        2023              72        107
79        Women's World Cup        2019              72         30

## Session 2: Loading a full match

In [4]:
matches = sb.matches(competition_id=53, season_id=315)
matches.shape

C:\Users\georg\OneDrive\Desktop\Portfolio\womens-football-dashboard\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(31, 55)

In [5]:
england = matches[
    matches["home_team"].str.contains("England")
    matches["away_team"].str.contains("England")
    ]
enfland[["match_id", "match_date", "home_team", "home_score", "away_score", "away_team"]].sort_values("match_date")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3450730906.py, line 2)

In [6]:
england = matches[
    matches["home_team"].str.contains("England") |
    matches["away_team"].str.contains("England")
]
england[["match_id", "match_date", "home_team", "home_score", "away_score", "away_team"]].sort_values("match_date")

,match_id,match_date,home_team,home_score,away_score,away_team
27,3998843,2025-07-05,France Women's,2,1,England Women's
18,3998851,2025-07-09,England Women's,4,0,Netherlands Women's
11,3998858,2025-07-13,England Women's,6,1,Wales W
9,4018355,2025-07-17,Sweden Women's,2,2,England Women's
6,4020005,2025-07-22,England Women's,2,1,Italy Women's
4,4020846,2025-07-27,England Women's,1,1,Spain Women's

In [7]:
events = sb.events(match_id=4020846)
events.shape

C:\Users\georg\OneDrive\Desktop\Portfolio\womens-football-dashboard\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(4830, 88)

In [8]:
events["type"].value_counts()

type
Pass                 1306
Ball Receipt*        1147
Carry                1032
Pressure              646
Ball Recovery         136
Clearance              84
Duel                   73
Block                  64
Goal Keeper            53
Shot                   40
Interception           34
Miscontrol             32
Dribble                29
Foul Committed         29
Foul Won               29
Dispossessed           25
Dribbled Past          14
Injury Stoppage        13
Half Start             10
Half End               10
Substitution            9
Starting XI             2
Shield                  2
50/50                   2
Referee Ball-Drop       2
Tactical Shift          2
Player Off              2
Player On               2
Error                   1
Name: count, dtype: int64

In [9]:
shots = events[events["type"] == "Shot"]
shots[["minute", "period", "team", "player", "shot_outcome", "shot_statsbomb_xg"]]

,minute,period,team,player,shot_outcome,shot_statsbomb_xg
4585,2,1,England Women's,Alessia Russo,Saved,0.064153
4586,8,1,Spain Women's,Esther Gonzalez Rodríguez,Saved,0.130437
4587,10,1,Spain Women's,Esther Gonzalez Rodríguez,Off T,0.102305
4588,12,1,Spain Women's,Athenea del Castillo Belvide,Blocked,0.067261
4589,13,1,England Women's,Georgia Stanway,Saved,0.059948
4590,18,1,England Women's,Lauren Hemp,Saved,0.330250
4591,20,1,Spain Women's,María Francesca Caldentey Oliver,Off T,0.052309
4592,24,1,Spain Women's,María Francesca Caldentey Oliver,Goal,0.395652
4593,25,1,England Women's,Keira Walsh,Off T,0.052506
4594,38,1,Spain Women's,Athenea del Castillo Belvide,Blocked,0.028371
4595,40,1,Spain Women's,Esther Gonzalez Rodríguez,Off T,0.071709
4596,42,1,England Women's,Ella Toone,Blocked,0.053555
4597,42,1,England Women's,Chloe Kelly,Off T,0.035819
4598,49,2,Spain Women's,Aitana Bonmati Conca,Saved,0.063976
4599,51,2,Spain Women's,María Francesca Caldentey Oliver,Saved,0.099360
4600,54,2,Spain Women's,Alexia Putellas Segura,Off T,0.069630
4601,56,2,England Women's,Alessia Russo,Goal,0.213453
4602,59,2,Spain Women's,Irene Paredes Hernandez,Saved,0.053010
4603,60,2,Spain Women's,Aitana Bonmati Conca,Blocked,0.040577
4604,66,2,Spain Women's,Athenea del Castillo Belvide,Off T,0.019896
4605,68,2,England Women's,Chloe Kelly,Saved,0.072824
4606,73,2,Spain Women's,Claudia Pina Medina,Saved,0.084166
4607,89,2,Spain Women's,Salma Paralluelo Ayingono,Blocked,0.028666
4608,90,2,Spain Women's,Aitana Bonmati Conca,Blocked,0.056714
4609,90,2,Spain Women's,Salma Paralluelo Ayingono,Off T,0.012767
4610,92,2,Spain Women's,Victoria López,Off T,0.063362
4611,96,3,Spain Women's,Aitana Bonmati Conca,Blocked,0.055494
4612,100,3,Spain Women's,Claudia Pina Medina,Off T,0.053868
4613,106,3,Spain Women's,Salma Paralluelo Ayingono,Wayward,0.400212
4614,112,4,Spain Women's,Victoria López,Off T,0.084615
4615,116,4,Spain Women's,Victoria López,Wayward,0.101625
4616,120,5,England Women's,Bethany Mead,Saved,0.783500
4617,121,5,Spain Women's,Patricia Guijarro Gutiérrez,Goal,0.783500
4618,122,5,England Women's,Alex Greenwood,Goal,0.783500
4619,123,5,Spain Women's,María Francesca Caldentey Oliver,Saved,0.783500
4620,124,5,England Women's,Niamh Charles,Goal,0.783500
4621,124,5,Spain Women's,Aitana Bonmati Conca,Saved,0.783500
4622,125,5,England Women's,Leah Williamson,Saved,0.783500
4623,126,5,Spain Women's,Salma Paralluelo Ayingono,Off T,0.783500
4624,127,5,England Women's,Chloe Kelly,Goal,0.783500

In [10]:
shots[shots["period"] == 5][["team", "player", "shot_outcome"]]

                 team                            player shot_outcome
4616  England Women's                      Bethany Mead        Saved
4617    Spain Women's       Patricia Guijarro Gutiérrez         Goal
4618  England Women's                    Alex Greenwood         Goal
4619    Spain Women's  María Francesca Caldentey Oliver        Saved
4620  England Women's                     Niamh Charles         Goal
4621    Spain Women's              Aitana Bonmati Conca        Saved
4622  England Women's                   Leah Williamson        Saved
4623    Spain Women's         Salma Paralluelo Ayingono        Off T
4624  England Women's                       Chloe Kelly         Goal

In [11]:
match_goals = shots[(shots["shot_outcome"] == "Goal") & (shots["period"] < 5)]
match_goals[["minute", "team", "player"]]

      minute             team                            player
4592      24    Spain Women's  María Francesca Caldentey Oliver
4601      56  England Women's                     Alessia Russo